title: Michael Retta # your name (or website title) here
logo: "/images/20230226_144018.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I love delivering data-driven insights and solutions. 
  <br><br>
  <a href="https://www.linkedin.com/in/michaelretta/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
